"""The committed baseline world (span=union__case=A), regenerated with the vectorised engine.

Item 12 of the v2 plan. The world's null was generated by
scripts/run_null_local.py (seed 42; exact enumeration for 328, 398, 454,
917; 10,000 sampled permutations otherwise) and summarised by
aggregate.py --local under every summary spec. The two null parquets are
git-ignored (80 MB); everything derived from them is committed and the
generation is deterministic, which ``test_regenerating_a_patient_reproduces_the_committed_summary``
checks without the parquets.
"""

from __future__ import annotations

import json

import numpy as np
import pandas as pd
import pytest

from aamos_concordance import null_from_per_config
from aamos_concordance.engine import run_patient_exact, run_patient_sampled
from aamos_concordance.summary import ALL_SPECS, PRIMARY, V1_SPEC, SummarySpec, available_specs, derive_concordant_sets, select
from aamos_concordance.worlds import (
    BASELINE, PER_CONFIG_Z, SUMMARY_CSV, concordant_sets_path, list_worlds, read_world_config, world_dir,
)
from tests.test_summary import V1_ASSESSED, V1_CONCORDANT_MEAN, V1_CONCORDANT_MEDIAN

# Sets under the primary spec (effective/spearman) on the regenerated null.
BASELINE_CONCORDANT_MEAN = [702, 917]
BASELINE_CONCORDANT_MEDIAN = [190, 294, 702, 917]
EXACT_PATIENTS = {328: 136, 398: 12650, 454: 840, 917: 2520}

# The committed baseline world was built under the v1 measurement definitions
# (open chunk end, code 12 in the 9-12 band, three Spearman method classes).
pytestmark = pytest.mark.usefixtures("v1_definitions_module")


@pytest.fixture(scope="module")
def baseline_dir():
    d = world_dir(BASELINE)
    assert d.is_dir(), "baseline world not built"
    return d


@pytest.fixture(scope="module")
def summary(baseline_dir):
    return pd.read_csv(baseline_dir / SUMMARY_CSV)


def test_baseline_per_config_table_is_v1_verbatim(baseline_dir, frozen_results_dir):
    ours = pd.read_csv(baseline_dir / PER_CONFIG_Z)
    v1 = pd.read_csv(frozen_results_dir / "per_patient_analysis" / "per_patient_correlation_results.csv")
    pd.testing.assert_frame_equal(ours, v1)


def test_baseline_config_records_engine_and_exact_modes(baseline_dir):
    cfg = read_world_config(BASELINE)
    assert cfg["world_id"] == "span=union__case=A" and cfg["null_engine"] == "vectorised"
    modes = {int(k): v for k, v in cfg["null_modes"].items()}
    for pid, n in EXACT_PATIENTS.items():
        assert modes[pid] == {"mode": "exact", "n_permutations": n}
    assert all(v["mode"] == "sampled" and v["n_permutations"] == 10000 and v["seed"] == 42
               for pid, v in modes.items() if pid not in EXACT_PATIENTS)


def test_baseline_summary_has_every_spec(summary):
    assert {sp.key for sp in available_specs(summary)} == {sp.key for sp in ALL_SPECS}
    assert sorted(summary["patient_id"].unique()) == V1_ASSESSED
    for pid, n in EXACT_PATIENTS.items():
        assert (summary[summary.patient_id == pid]["n_permutations"] == n).all()


def test_baseline_summary_yields_the_primary_sets(summary):
    sets = derive_concordant_sets(summary)
    assert sets[PRIMARY.key] == BASELINE_CONCORDANT_MEAN
    assert sets[SummarySpec("effective", "spearman", "median").key] == BASELINE_CONCORDANT_MEDIAN
    # all/spearman on the regenerated null agrees with the centred rule on the v1 null
    assert sets[V1_SPEC.key] == V1_CONCORDANT_MEAN
    assert sets[SummarySpec("all", "spearman", "median").key] == V1_CONCORDANT_MEDIAN


def test_generated_concordant_sets_file_matches_summary(summary):
    sets = json.loads(concordant_sets_path().read_text())["span=union__case=A"]
    assert sets == derive_concordant_sets(summary)
    assert "span=union__case=A" in list_worlds()


def test_no_leaked_perfect_correlations_in_the_regenerated_summary(summary):
    """The v1 null had |Z| ~ 18 leaks for 328/398/454/917; the engine records those as invalid."""
    assert summary["null_mean"].abs().max() < 1.5
    s398 = select(summary, V1_SPEC).set_index("patient_id").loc[398]
    assert -0.4 < s398["null_mean"] < -0.1  # was -1.45 on the v1 null


def test_config_groups_use_the_primary_spec_without_fallback(restore_active_world):
    import warnings
    import config
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        config.set_active_world(BASELINE)
    assert config.ACTIVE_SPEC == PRIMARY
    assert config.GROUPS["concordant"]["patients"] == BASELINE_CONCORDANT_MEAN
    assert config.GROUPS["concordant"]["summary_spec"] == "effective/spearman/mean"
    assert config.GROUPS["median_concordant"]["patients"] == BASELINE_CONCORDANT_MEDIAN
    assert config.ASSESSED_PATIENTS == V1_ASSESSED
    config.set_active_world(BASELINE, summary="all/spearman")
    assert config.GROUPS["concordant"]["patients"] == V1_CONCORDANT_MEAN
    config.set_active_world(BASELINE)


@pytest.fixture
def restore_active_world():
    import config
    yield
    config.set_active_world(BASELINE)


def test_set_active_world_rejects_unbuilt_world(restore_active_world):
    import config
    with pytest.raises(RuntimeError, match="No concordant sets recorded"):
        config.set_active_world("span=intersection__case=B__k=99")  # never built
    assert config.ACTIVE_WORLD == BASELINE


def test_output_dirs_are_per_world(tmp_path, monkeypatch):
    import config
    from aamos_concordance import worlds
    config.set_active_world(BASELINE)
    monkeypatch.setattr(worlds, "V2_DIR", tmp_path)  # only affects path resolution; active world untouched
    assert config.get_output_dir("concordant", "bland_altman") == tmp_path / "comparisons" / "span=union__case=A" / "concordant" / "bland_altman"


def test_baseline_observed_and_sweep_files_exist(baseline_dir):
    observed = pd.read_csv(baseline_dir / "observed.csv")
    assert set(observed["config_set"]) == {"all", "effective"} and set(observed["correlation_type"]) == {"spearman", "pearson"}
    eff = observed[(observed.config_set == "effective") & (observed.correlation_type == "spearman") & (observed.measure == "mean")].set_index("patient_id")
    assert (eff["n_valid_configs_observed"] <= 60).all()
    assert eff.loc[473, "observed_z"] == pytest.approx(0.432, abs=5e-4)
    sweep = pd.read_csv(baseline_dir / "threshold_sweep.csv")
    row = sweep[(sweep.config_set == "effective") & (sweep.correlation_type == "spearman") & (sweep.measure == "mean")].set_index("threshold")["concordant"]
    assert row.loc[0.5] == "702 917" and row.loc[0.75] == "917" and row.loc[0.9] == "917"


@pytest.mark.parametrize("patient_id", [917, 454])
def test_regenerating_a_patient_reproduces_the_committed_summary(data_dir, summary, patient_id):
    """Determinism without the 80 MB parquet: regenerate one exact-enumeration patient and re-derive its rows."""
    from aamos_concordance.summary import observed_statistics, permutation_p_values
    q = pd.read_csv(data_dir / "anonym_aamos00_dailyquestionnaire_dt.csv")
    inh = pd.read_csv(data_dir / "anonym_aamos00_smartinhaler_dt.csv")
    qq, ii = q[q.user_key == patient_id], inh[inh.user_key == patient_id]
    pc = run_patient_exact(patient_id, qq, ii)
    per_config = pd.read_csv(world_dir(BASELINE) / PER_CONFIG_Z)
    for spec in (PRIMARY, V1_SPEC, SummarySpec("all", "pearson", "median")):
        null = null_from_per_config(pc, correlation_type=spec.correlation_type, config_indices=spec.config_indices)
        obs = observed_statistics(per_config, f"{spec.correlation_type}_z", spec.config_indices).set_index("patient_id")
        row = permutation_p_values(obs[spec.measure], null, null_column=f"null_{spec.measure}_z",
                                   n_patients=15).set_index("patient_id").loc[patient_id]
        committed = select(summary, spec).set_index("patient_id").loc[patient_id]
        for col in ("observed_z", "p_value", "null_mean", "null_std", "n_permutations", "n_ties_at_observed"):
            assert row[col] == pytest.approx(committed[col], abs=1e-9), (spec.key, col)
